### ISSUE TITLE
Agree on API for staking and rewards Javascript-golang

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#3113] opened 2021-05-17 18:59 UTC
We need an API between Javascript and golang to update Javascript about changes in staking assignments, and inform golang about reward for blocks and epochs. The [discussion is recorded](https://docs.google.com/document/d/18UTho2CjFwEf8ZkEyVOua1WZRPp-yizzTD1PnkGqn3Y/edit#) in a Google doc.

The issue to track the Javascript implementation is #3114

**Comment by michaelfig** [comment] 2021-05-28 06:17
We sidestepped this issue by using the `x/distribution` module as it was intended, and just putting bank purse assets into the `feeCollector` for F1 distribution.

Closing until we figure we need to do something different for staking and rewards.

**Closed as completed by michaelfig** 2021-05-28 06:17 UTC
Labels: enhancement, Core Economy
