### ISSUE TITLE
Consider adding a convention for zoe seats for running something when the invite is redeemed

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#783] opened 2020-03-26 15:52 UTC
Currently, a couple contract tests follow a pattern like:
```js
const {seat, payoutP} = zoe.redeem(invite, proposal, payments)

cons result = seat.someMethod() // like "addOffer()" (no argument)

payoutP
.then(payout => console.log('cool', payout))
.catch(err => console.error('oops', err))
```

There is an assert on the `result`, but it's quite useless otherwise
I feel like `someMethod` exists only to indicate the contract that the user is ready to participate
But for (i imagine) lots of contracts, `alice.redeem(invite, proposal, payments)` is already a good indication that the person is ready, there shouldn't be a need for an additional opt-in

One possible solution could be a convention for a seat method name. Something like `onInviteRedeem`. If a seat has a method with this name, zoe calls the method automatically when the person successfully redeemed an invite (and errors from call to this method are propagated to `payoutP.catch`)

As a consequence, Alice code would look like:
```js
const {payoutP} = zoe.redeem(invite, proposal, payments)

payoutP
.then(payout => console.log('cool', payout))
.catch(err => console.error('oops', err))
```

I feel this better reflects Alice intent ("i see an invite, i inspect it, if i'm interested, i send a proposal and the corresponding payment. I get want i want in the payout or an explanation of why that didn't work")

Contracts that don't want to use this convention just choose to never call a method `onInviteRedeem` on seats

**Comment by michaelfig** [comment] 2020-03-26 16:25
This is a duplicate of #717.  Closing.

**Closed as completed by michaelfig** 2020-03-26 16:25 UTC
Labels: Zoe

**Comment by DavidBruant** [comment] 2020-03-26 16:55
oh i had not understood the what upcall was about!
Thanks for the triage!
