### ISSUE TITLE
Incorporate rounding best practices into our AMM

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#3064] opened 2021-05-10 17:18 UTC

**Comment by Chris-Hibbert** [comment] 2021-05-10 21:53
We haven't codified this anywhere, but the consensus seems to be that a safe pattern of use for `reallocate()` is to ensure that any amount added and subtracted to one seat in a `reallocate()` has to have a corresponding subtraction or addition on another seat.

There are six paths through `swap` in the newSwap code.  Each of `swapIn` and `swapOut` has a separate branch for from RUN, to RUN, and secondary to secondary. Both `swapIn` and `swapOut` start with a single call to `getCurrentPrice()` to get `amountIn`, `amountOut`, `protocolFee`, and when the trade is secondary-to-secondary, `centralAmount`.  In both `swapIn` and `swapOut`, `protocolFee` is added to the protocol seat and the user's seat is adjusted by subtracting `amountIn` and adding `amountOut`. 

## SwapIn

`amountIn` is replaced by `reducedAmountIn`.
We add `amountOut` and subtract `reducedAmountIn`, so the branches below need to do the opposite.
`+protocolFee`, `+amountOut`, `-reducedAmountIn`

**a bug was discovered here: `amountIn` was used instead of `reducedAmountIn` in one place. fixed in #3060**

### From RUN

`poolStagingFromCentral` adds `amountMath.subtract(reducedAmountIn, protocolFee)`  and subtracts `amountOut`.
`-protocolFee`, `-amountOut`, `+reducedAmountIn`

### To RUN

`poolStagingToCentral` subtracts `amountMath.add(amountOut, protocolFee)`  and adds `reducedAmountIn`.
`-protocolFee`, `-amountOut`, `+reducedAmountIn`

### Secondary to secondary

secondaryPoolStagings adjusts two pools:
brandInPool adds `amountIn`, and subtracts `amountMath.add(centralAmount, protocolFee)` 
brandOutPool adds `centralAmount`, and subtracts `amountOut`

`+amountIn`, `-centralAmount`, `protocolFee`, `+centralAmount`, `-amountOut`

## SwapOut

`amountOut` is replaced with `improvedAmountOut`.
We add `improvedAmountOut` and subtract `amountIn`, so the branches below need to do the opposite.
`+protocolFee`, `+improvedAmountOut`, `-amountIn`

### From RUN

`poolStagingFromCentral` adds `amountMath.subtract(reducedAmountIn, protocolFee)`  and subtracts `improvedAmountOut`.
`-protocolFee`, `-improvedAmountOut`, `+reducedAmountIn`

### To RUN

`poolStagingToCentral` subtracts `amountMath.add(improvedAmountOut, protocolFee)`  and adds `reducedAmountIn`.
`-protocolFee`, `-improvedAmountOut`, `+reducedAmountIn`

### Secondary to secondary

secondaryPoolStagings adjusts two pools:
brandInPool adds `amountIn`, and subtracts `amountMath.add(centralAmount, protocolFee)` 
brandOutPool adds `centralAmount`, and subtracts `amountOut`

`+amountIn`, `-centralAmount`, `protocolFee`, `+centralAmount`, `-amountOut`

**Comment by Chris-Hibbert** [comment] 2021-05-10 21:55
I'll amplify a statement I put in bold above: There was a bug in `swapIn`, that replaced one instance of `reducedAmountIn` with `amountIn`. My first round of fixes above, mainly addressed at the offer safety problems, made those two values the same, which hid the underlying rights conservation issue.

**Comment by katelynsills** [comment] 2021-05-12 23:05
Here's an idea for an alternative `reallocate` API that I think makes rights conservation a lot clearer. For instance, for the `SwapIn secondary to secondary` case which is currently 28 lines in MultipoolAutoswap, we could instead do:

```js
// Take what the user gave (though slightly reduced) and add it to that brand's pool
seat.subtract({ In: reducedAmountIn });
brandInPool.add({ Secondary: reducedAmountIn });

// Subtract what the user will get as a payout and add it to the user's seat
brandOutPool.subtract({ Secondary: amountOut });
seat.add({ Out: amountOut });

// Transfer the centralAmount from the brandIn to brandOutPool
brandInPool.subtract({ Central: reducedCentralAmount });
brandOutPool.add({ Central: reducedCentralAmount });

// Finally, reallocate over all three seats, given these stagings by brand
reallocate(seat, brandInPool, brandOutPool);
```
This is less than 10 lines (not including comments) and I think you can easily inspect it for rights conservation errors. 

We would need to move the offer safety checks back to the `reallocate` step but I think that's fine.

**Comment by katelynsills** [comment] 2021-05-12 23:43
Another alternative is if the `.subtract` returns the amount subtracted, which can be used as the `add` argument: 

```js
brandInPool.add({ Secondary: seat.subtract({ In: reducedAmountIn }) });
seat.add({ Out: brandOutPool.subtract({ Secondary: amountOut }) });
brandOutPool.add({ Central: brandInPool.subtract({ Central: reducedCentralAmount }) });
reallocate(seat, brandInPool, brandOutPool);
```
Harder to read, but maybe more robust?

**Comment by dtribble** [comment] 2021-05-18 03:29
I like these. And then any change made that is not included in a reallocate could also be an error, so you can prepare something and leave it out. It has interim state, but is very clear. I tried a few variants with a `transfer` operation. It's plausible to me that that would be safer still, but I couldn't come up with an API that seemed clear.

**Comment by Chris-Hibbert** [comment] 2021-05-19 16:45
I'm not sure that putting off the offer safety check is a real win. I think it's easier to keep track of rights conservation (our recent refactorings have shown that once we're paying attention, it straightforward to write the `reallocate/trade/swap` so it's clear that what is taken from one seat is given to another.

I think tracking offer safety is more delicate and benefits from the current up-front check in reallocate. If the check were made later, then it would be possible to create collection of seats that conserve rights, but includes transfers that will be rejected later for offer safety reasons, obscuring the cause of the problem.

I like the simplifications above, but not the implication that offer safety can be verified later.

**Comment by katelynsills** [comment] 2021-06-09 04:34
I think we can close this issue, as both newSwap and multipoolAutoswap use the new reallocate API now. Conservation of rights can be much more easily observed by reading the code.

**Closed as completed by katelynsills** 2021-06-09 04:34 UTC
