### ISSUE TITLE
Make purses virtual objects

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#2841] opened 2021-04-08 22:08 UTC

**Comment by katelynsills** [comment] 2021-04-08 22:53
See https://github.com/Agoric/agoric-sdk/issues/1830 for the overall plan which this is part of.

**Comment by katelynsills** [comment] 2021-08-05 01:14
ERTP will not be using virtual objects at the time of our audit.

**Comment by Chris-Hibbert** [comment] 2022-02-08 23:16
This is now a duplicate of #4504, which we'll use going forward.

**Closed as completed by Chris-Hibbert** 2022-02-08 23:16 UTC
Labels: ERTP, performance
