### ISSUE TITLE
get all packages eslint-clean

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#457] opened 2020-01-27 19:49 UTC
Our CI currently only runs `eslint` on a few packages that are known to be lint-clean: `marshal`, `SwingSet`, `ERTP`, and `Zoe`.

We should get everything else lint-clean, and expand that to cover all packages.

You can run `yarn lint-check-all` from the top of the tree to attempt eslint on everything. From within any given package, you can run `yarn lint-check` to test just that one package.

When we're done, we can replace the top-level `lint-check` definition with one that just runs `yarn workspaces run lint-check`.

We might want to write some common tooling to which all packages' `package.json` can delegate their behavior, and make sure as little unique code is present in the individual package directories.

Packages which are currently eslint-clean:

* [x] acorn-eventual-send
* [x] eventual-send
* [x] transform-eventual-send
* [x] default-evaluate-options
* [x] evaluate
* [x] bundle-source
* [x] marshal
* [x] captp
* [x] SwingSet
* [x] ERTP
* [x] zoe
* [x] cosmic-swingset
* [x] agoric-cli (which also has some template subdirectories)
* [x] deployment

**Comment by katelynsills** [comment] 2020-01-27 19:54
So far in some packages we have optional jessie linting in package.json scripts:

```
    "lint-fix": "eslint --fix '**/*.{js,jsx}'",
    "lint-check": "eslint '**/*.{js,jsx}'",
    "lint-fix-jessie": "eslint -c '.eslintrc-jessie.js' --fix '**/*.{js,jsx}'",
    "lint-check-jessie": "eslint -c '.eslintrc-jessie.js' '**/*.{js,jsx}'"
```

To be able to run lint-fix-jessie only on some files immediately, we could use the configuration settings  to [disable rules for a group of files](https://eslint.org/docs/user-guide/configuring#disabling-rules-only-for-a-group-of-files)

**Comment by warner** [comment] 2020-01-28 03:31
I've gotten most of the packages to be eslint-clean, and updated package.json to check them. Still to do:

* make cosmic-swingset eslint-clean
* fix all the `package.json` files to only lint our own source files, not everything in the `node_modules` directories (I think that might fix the problems with `agoric-cli`)
* add a lint-check target to `deployment`
* update the lint-fix rules
* consolidate the prettier-check/prettier-fix targets (maybe remove them? do we need both eslint-fix and prettier-fix?)

**Comment by warner** [comment] 2020-01-28 21:47
Any thoughts on whether I should move the linting stuff up to the top level? So rather than a top-level `yarn lint-check` using `yarn workspace run` to execute a lint-check in each package, it would run eslint exactly once and just examine all packages at the same time? (This assumes we get everything lint-clean first, so the steady-state should be no warnings). I can see workflow fallout: if it's centralized, then as you develop a feature you're iterating on editing and running `yarn test` in a single subpackage, but then before you commit you'd have to jump up to the top level and run `yarn lint` or `yarn lint-fix`.

If it's at the top-level, then to exclude e.g. `cosmic-swingset`, we'd use `.eslintignore` on the whole sub-package, rather than changing `package.json` to only invoke `eslint` on all the *other* subpackages.

**Comment by katelynsills** [comment] 2020-01-28 22:12
I think having to move up to root before running `yarn lint` is pretty costly, so any way of avoiding that would be great! 

Btw, not sure how helpful this is, but if you like Portuguese, this guy apparently has set up a separate package specifically for his ESLint config within the monorepo: https://robertoachar.dev/blog/yarn-workspaces-eslint

**Comment by erights** [comment] 2020-02-11 04:09
A `yarn run lint-fix` at the top missed at least swingset, pixel-demo, spawner, and zoe. Swingset and zoe are on the above list of packages that should have been fixed from the top.

**Comment by erights** [comment] 2020-02-11 05:58
@warner Nevermind. I think this was caused by an unrelated error on the branch I am on. Sorry!

**Comment by warner** [comment] 2020-02-15 01:27
BTW we should use the `.json` config style for eslint, because the upcoming module-ification will reject the commonjs-style `.eslintrc.js` format we're currently using.

**Comment by warner** [comment] 2020-02-18 19:39
@FUDCo is going to clean up the CI and mark the not-yet clean files in `.eslintignore`, and then make a note here about what remains to be done.

**Comment by FUDCo** [comment] 2020-02-19 01:18
Did that.  See PR #569.

Replaced the complicated, lengthy, manually maintained (and error attracting) `lint-fix` script in the top level `package.json` with a simple yarn workspaces command.  This way, when new packages are added, the CI will not overlook linting them.  Also added `lint-fix` scripts for existing packages that didn't have them.  The `lint-fix` script in packages that don't yet pass lint doesn't try to actually run `eslint` but instead outputs a warning message.  This keeps us alerted that these packages still have cleanup work remaining to be done, but allows them to continue to be used. 

Note that `.eslintignore` was not used because `eslint` errors out if told to ignore all files in a package.

**Comment by Chris-Hibbert** [comment] 2020-03-16 16:42
In [a PR to clean up some eslint rules](https://github.com/Agoric/agoric-sdk/pull/697), I wrote: 
> Placing [eslint] exceptions [at the top of a file] makes me uncomfortable. We should only enforce these rules if we feel strongly enough that they're the right convention that we want to them to apply in all but exceptional circumstances. We should either require documenting why an exception is necessary in a particular case, or drop the rule.

> I think no-continue is a fine rule, and I would favor enforcing it here.

> My impression is that no-await-in-loop is generally a good rule, and exceptions should be documented locally where they occur and not globally over a file.

**Comment by FUDCo** [comment] 2020-03-16 17:32
I'm on board with the idea that there should be a single set of eslint rules we use universally, but we should definitely have a conversation about which rules we want.  Personally I'm in favor of eliminating `no-else-return`, `no-lonely-if`, and `prefer-destructuring`.

The first two are bad because I think the consequences of a given conditional should all be at the same level of indentation.

`no-else-return` prevents me from writing
```
if (condition) {
  return thing1;
} else {
  return thing2;
}
```
preferring instead
```
if (condition) {
  return thing1;
}
return thing2;
```
which requires extra thought to read.

In the same vein, `no-lonely-if` prevents me from writing
```
if (condition) {
  if (subcondition) {
    doThing1a;
  } else {
    doThing1b;
  }
} else {
  if (subcondition) {
    doThing2a;
  } else {
    doThing2b;
  }
}
```
but instead wants
```
if (condition) {
  if (subcondition) {
    doThing1a;
  } else {
    doThing1b;
  }
} else if (subcondition) {
  doThing2a;
} else {
  doThing2b;
}
```
which is simply terrible.

The `prefer-destructuring` rule is a bit trickier.  Better would be if the rule were there but only applied when assigning to multiple variables.  As it is, it complains about:
```foo = thing.foo```
wanting instead
```{ foo } = thing;```
which is weird and confusing.  Even worse is
```foo = arr[0];```
where the rule instead wants
```[foo] = arr;```
which is just bizarre.

Also mildly objectionable are some applications of the `object-shorthand` rule, where a slightly complicated object creation such as, e.g.
```
return {
  foo: complicatedTransform(foo),
  bar: bar,
  baz: interestingTransform(baz),
};
```
provokes a whinge that it should be
```
return {
  foo: complicatedTransform(foo),
  bar,
  baz: interestingTransform(baz),
};
```
Once again, I think things that are lexically parallel should be allowed to have lexically parallel forms.  I understand if you are assigning a bunch of properties all from variables with the same names, e.g.,
```
return {
  foo,
  bar,
  baz,
};
```
then the `object-shorthand` rule makes sense, which is why my objections in this case are milder.

**Comment by FUDCo** [comment] 2020-03-16 17:52
And I just encountered another bit of stupid from `prettier`.  I had a conditional that was checking a variable that could have one of two possible values.  I marked the else case with a comment indicating the alternative condition:
```
if (type === 'png') {
  doStuff();
} else /* if (type === 'pdf') */ {
  doDifferentStuff();
}
```
But this is unacceptable to `prettier`.  It wants
```
if (type === 'png') {
  doStuff();
} /* if (type === 'pdf') */ else {
  doDifferentStuff();
}
```
Which is simply _*wrong*_.

I could have written
```
if (type === 'png') {
  doStuff();
} else if (type === 'pdf') {
  doDifferentStuff();
} else {
  throw new Error(`invalid type value ${type}`);
}
```
which has much to recommend it, but that exact value check (with throw for the invalid value) already took place several lines above.

**Comment by Chris-Hibbert** [comment] 2020-03-16 18:01
The thing I object to more about prettier doesn't seem to be configurable. prettier seems to prefer breaking at the last possible place on a line. I successfully argued at Google that the prettifier we used for Java should prefer breaks at the highest syntantic level.

When an assignment overflows the line length by a character or two, I want a newline after the `=`, not to break up the parameter list into multiple lines. There are lots of other cases.

Here's an arbitrary example.
```
    const { invite } = await E(zoe).makeInstance(installations.simpleExchange, roles);
```
is too long, and prettier wants
```
    const { invite } = await E(zoe).makeInstance(
      installations.simpleExchange,
      roles,
    );
```
rather than
```
    const { invite } =
      await E(zoe).makeInstance(installations.simpleExchange, roles);
```

**Comment by FUDCo** [comment] 2020-03-16 18:06
I agree strongly about the line splitting heuristic.

I've had so many issues with prettier, I'm wondering if there's an alternative that we could simply switch to.

**Comment by Chris-Hibbert** [comment] 2020-03-16 18:10
+10

I would actually prefer allowing people to format their own code over what we get from prettier.

**Comment by michaelfig** [comment] 2020-03-16 18:21
For people like me who have used prettier for a long time, it is annoying to work with code that doesn't have a consistent style.  Your recommendations are interesting, but unless we have the tools to enforce them, they are just personal deviations that not everybody wants to follow.  Configuring the tools differently is fine, so long as they're applied Agoric-wide.

Golang, which has tools to enforce style much like prettier, is pleasant to read and write mainly because there's a consistent style that is never deviated from.  It's much less important *what* the style is than that there is one.

**Comment by FUDCo** [comment] 2020-03-16 18:35
Just to be clear, I'm also in favor of having a consistent style.  My issue is that prettier's particular stylistic opinions are often wrong in ways that make our code visibly worse if we follow them.

**Comment by michaelfig** [comment] 2021-03-18 05:03
This is done.

**Closed as completed by michaelfig** 2021-03-18 05:03 UTC
Labels: cosmic-swingset, agoric-cli, hygiene
