### ISSUE TITLE
Make offer results directly accessible as part of the wallet API

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#2058] opened 2020-12-01 00:33 UTC
**What is the Problem Being Solved?**

Dapps that make offers via the wallet should be able to manipulate the results, whether data or ocaps.  Likewise, the user should also be able to manipulate these results via the REPL (and possibly also an advanced UI in the future).

**Description of the Design**

Add offer results to the offer records that are exposed via something like an offer notifier (part of #2032).  For completeness, the completion/cancellation object should also be accessible.

In order to complete the circuit, dapp UIs can use CapTP to manipulate these objects directly.  An alternative way is to use the rendezvous service (#1861) in the dapp backend (if there is one), which can reach them from the same APIs.

**Security Considerations**

Current constraints prevent dapps from inspecting offer records that were made by other origins.  The REPL (and hence deployment scripts) has no such restriction, but this should be revisited in a more comprehensive deployment script audit.

**Test Plan**

Validate that a dapp UI can manipulate an ocap offer result without requiring any additional support outside of the wallet bridge itself.

**Comment by katelynsills** [comment] 2020-12-01 00:45
> Dapps that make offers via the wallet should be able to manipulate the results, whether data or ocaps.

I believe this breaks Zoe's security assumptions and design. The `offerResult` should be under the sole control of the user who made the offer and should remain in the user's wallet, for the same reasons that the dapp does not make direct offers on the user's behalf nor does the dapp hold digital assets for the user. Please do not move forward with this design! 

Instead, I think we should 1) create a a generic ocap UI that allows the user to visually explore and execute ocap methods, and 2) brainstorm ways to for the dapp to propose actions to be taken with an ocap. I expect that this will take time to think through properly, but it might include: the dapp sending code to the wallet to be run when an offerResult is received, or the dapp learning (with the user's permission) what methods an ocap has and suggesting a method to call. Importantly, the dapp should only learn about an offerResult with the user's consent.

**Comment by michaelfig** [comment] 2020-12-01 01:03
> Importantly, the dapp should only learn about an offerResult with the user's consent.

Thanks, that's valuable to understand.

To what extent are we already violating this principle by allowing the dapp UI to manipulate the (JSON-laundered) offer result, such as dapp-encouragement's encouraging message?  Or are you saying that the only issue is if the result contains a directly-manipulable ocap?

**Comment by katelynsills** [comment] 2020-12-01 01:20
> To what extent are we already violating this principle by allowing the dapp UI to manipulate the (JSON-laundered) offer result, such as dapp-encouragement's encouraging message? Or are you saying that the only issue is if the result contains a directly-manipulable ocap?

That's a good point. I think it slipped past me, probably because the dapp-encouragement is so much of a toy example: the `offerResult` in that dapp doesn't contain hardly any authority. Ideally we probably want even string `offerResults` to only be sent back to the dapp with the user's permission, even though the authority (as far as I can imagine it) will be in limited with string `offerResults`.

With anything with more authority than a string, I think we need to treat it as if it is a valuable digital asset itself, as valuable as any other asset in the wallet, albeit not an ERTP-transferable one. 

The loan contract is a good example to use to work through the wallet design for a powerful `offerResult`. In the loan contract, the borrower gets an `offerResult` that allows the borrower to add more collateral, pay back the loan, and so forth. You don't want the dapp (which is probably run by the lender or someone potentially in cahoots with the lender) to control or get *any* access this, lest they make their own offers before you do! But, you do want the borrower to easily be able to click on a button that says "Add Collateral" and be able to make a Zoe offer in the wallet to do so.

**Comment by michaelfig** [comment] 2020-12-01 20:18
After sleeping on it, I'm not convinced that a generic ocap UI will be understandable enough for people to give informed consent, nor flexible enough to provide third-party UI for its manipulation.

I'd like to propose that powerful features on the result be phrased in terms of invitation-makers that require the offer of an NFT minted by the contract in order to exercise (as a bearer token).  Please take the rest of this suggestion as just a sketch; I am not wedded to the mechanics, and there are probably better names.

So, the loan contract may mint a "LoanTicket" NFT, each of which is represented as a string.  Upon creation of the loan, the contract will return some LoanTickets as a part of the payout: "add-collateral", "pay-back", etc.  The offer result would have things like `E(offerResult).makeAddCollateralInvitation(...)`, `E(offerResult).makePaybackInvitation(...)`, etc.

The dapp, reaching into the offer result, can create these invitations, but does not have access to the LoanTickets that are required as part of the offer for the loan contract to act on them.  Then, when the offer arrives in the user's wallet, they can inspect the proposal, see that it is an "addCollateral" invitation, see that it requires an "add-collateral" LoanTicket plus some $Collateral, and see that it corresponds to the specific loan instance they have a petname for.  Upon accepting the offer, the loan contract could send back the "add-collateral" LoanTicket to allow it to be used again: it need not be burned.

In that sense, this idea is one way "for the dapp to propose actions to be taken with an ocap" as you had asked, without introducing a second model into the wallet.

**Comment by katelynsills** [comment] 2020-12-01 20:35
I'm still processing the above, but I think we should focus on solutions that do not require redesigning the loan contract or Zoe mechanisms. Both have been carefully designed, whereas we know that the wallet and dapps have lacked the design attention that they need.

**Comment by katelynsills** [comment] 2020-12-02 00:17
I had an idea that I think would work: the wallet contains code snippets following POLA that can be run with the user's consent. This would get rid of a number of things we implemented that we know are design hacks, such as the dapp UI making a marshallable proposal with purse petnames and board ids and the dapp UI telling the wallet which invitation to use through a board id for the invitation handle.

To use the borrower offerResult as an example: the dapp developer could write a code snippet for “payback and close the loan” which is built from smaller code snippets with limited authority:
* `makeCloseLoanInvitation` which takes in a loan manager ocap (the offerResult) and a deposit facet for a Zoe invitation purse and which makes a close loan invitation
* `makeProposalToCloseLoan` which creates just the proposal record by getting the latest amounts of the debt and collateral
* `makeOfferToCloseLoan` which actually makes the offer to Zoe by putting together the proposal, the payments, the invitation, and the purses to deposit the payouts into.

Some of these snippets could be stored as part of the contract code and gotten from Zoe. Others might be created by the users themselves. But what this would mean is that a button on the dapp UI only needs to know the name of a code snippet to ask the wallet to execute.

I'm writing up a full problem description of the loan contract offerResult (separate from this ^ solution) and will link to it.

**Comment by katelynsills** [comment] 2020-12-02 01:08
Here's the write-up: https://docs.google.com/document/d/1RmdzzoHBLL6XV9_Sw3l4_IVgOBMqHMl0mdjtvoZ7bwk/edit# (I'll make a publicly accessible version soon)

**Comment by michaelfig** [comment] 2020-12-02 02:23
If the snippets have to be run with the user's consent, why not have a more direct interaction between the contract, the wallet, and the dapp?

Let the offer result be manipulated by the dapp, but add a method on a seat to ask the seat’s corresponding wallet UI for confirmation (or reject if not granted).  Offers made to Zoe via a wallet would include a callback object for these questions to be asked.  By default (without a wallet), these confirmations would be no-ops.  This puts the contract in control of what needs to be confirmed, makes the wallet responsible for UI interactions to obtain confirmation, and allows the dapp UI to use the offer result without violating the contract or the wallet.

**Comment by katelynsills** [comment] 2020-12-02 03:04
Hmm, I would like to understand this better. I think I may not be understanding it fully, but this seems more complicated and not in line with Zoe design. For instance:

> This puts the contract in control of what needs to be confirmed

The contract shouldn't be in control of what gets confirmed. The contract is suspect, which is why it never gets control of digital assets and why Zoe handles payouts. Compare this to the user consenting to execute reusable code snippets that are tightly bound to the least authority needed. The code snippets should be modular, meaning that probably many common ones are written by us and audited, even if the exact combination of them into a larger module is written by the dapp contract developer. 

> offer result be manipulated by the dapp, but add a method on a seat to ask the seat’s corresponding wallet UI for confirmation (or reject if not granted)

This doesn't seem to follow POLA. It seems like the user gets a yes/no vote on giving the dapp full access. 

> add a method on a seat

Does this mean a userSeat? I don't think we should change Zoe API to accommodate the UI. Compare this to the code snippets idea, in which we don't need to change how Zoe works at all, as far as I can tell. 

> Offers made to Zoe via a wallet would include a callback object for these questions to be asked

This seems to carve out a particular design for `offerResults`, whereas the code snippets concept solves the problem of `offerResults` *and* making invitations and proposals. I think we shouldn't have to design a special UI mechanism for each function. With the code snippets concept, we are actually using the Zoe API as intended.

**Comment by michaelfig** [comment] 2020-12-02 03:07
If you want to prevent a dapp UI from taking a trusted invitation and giving it to someone else, why not provide a way for the contract to control how the invitation is used?

Provide a method on the seat, like:
```js
seat.declareDappFacet(walletBridge => {
  makeOfferToCloseLoan() {
    const invite = makeCloseInvitation();
    E(walletBridge).addOffer(...);
  }
})
```
and let the wallet ask a seat for its dapp facet, passing in a bridge specific to that dapp.  Return that facet to the dapp UI (but not the offerResult), which can call methods on it and then the contract can ensure proposals happen only in the context of the wallet that asked for the dappFacet.  Then, the dapp UI can call whatever methods it wishes, without leaking the invitation to another wallet.

If somebody wants to bypass this ceremony, they can just use the offerResult directly.

**Comment by michaelfig** [comment] 2020-12-02 03:09
> Hmm, I would like to understand this better. I think I may not be understanding it fully, but this seems more complicated and not in line with Zoe design.

I'm still brainstorming.  Can we leave analysis for later?

**Comment by katelynsills** [comment] 2020-12-02 03:17
> I'm still brainstorming. Can we leave analysis for later?

I think further brainstorming is great, but I think github issues are also for analysis and we should welcome that too.

**Comment by zarutian** [comment] 2020-12-15 17:41
A prefered way to do „ticket check“ for dapps is to have like the following in the smart contract:

```javascript
const publicFacet = harden({
  // ... other public methods of the smart contract
  ticketCheck: (ticketID) => {
    const { promise, resolve, reject } = makePromiseKit();
    return harden({
      controler: promise,
      invitation: zcf.makeInvitation(seat => {
        // check that seat has the specified ticket
        // if so, revoke the previous controler
        // resolve `promise` to a new controler
        // otherwise, reject `promise` with error
        seat.exit();
        return undefined;
      }, "ticket check");
    });
  },
});
```
That way the dapp does not have to interact with the offerResult

**Comment by katelynsills** [comment] 2021-02-03 00:17
I think we can probably close this. What do you think @michaelfig?

**Closed as completed** 2021-02-03 18:59 UTC
Labels: enhancement, wallet
