### ISSUE TITLE
'Cannot convert a Symbol value to a string' Error when using `observeIteration` on remote asyncIterables

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2092] opened 2020-12-16 23:19 UTC
**Describe the bug**
 
In [dapp-loan](https://github.com/Agoric/dapp-loan) (currently private), I create an asyncIterable in a Zoe contract using `makeSubscriptionKit`, making it accessible through the public facet of the contract. However, when I attempt to use the asyncIterable with `observeIteration` in a deploy script, I get the the following error in the terminal I did `agoric start` in:

```
SwingSet: v2: Temporary logging of sent error (TypeError#5)

  TypeError#5: Cannot convert a Symbol value to a string
     at queueMessage (kernel/packages/SwingSet/src/kernel/liveSlots.js:310:50)
    at Object.applyMethod (kernel/packages/SwingSet/src/kernel/liveSlots.js:80:16)
    at Object.applyMethod (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:349:43)
    at doIt (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:395:67)
    at /Users/katesills/code/agoric-sdk/packages/eventual-send/src/track-turns.js:61:22
    at win (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:408:19)
    at /Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:425:20
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  
  TypeError#5 ERROR_NOTE: Thrown from: (Error#6) : 1195 . 0
  TypeError#5 ERROR_NOTE: Sent as error:captp:http://127.0.0.1#1
  TypeError#5
    Error#6: Event: 1194.1
       at trackTurns (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/track-turns.js:44:24)
      at handle (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:396:27)
      at Function.applyMethod (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:312:14)
      at Function.applyMethod (/Users/katesills/code/agoric-sdk/packages/tame-metering/src/tame.js:172:20)
      at CTP_CALL (v2/agoric-sdk/packages/captp/lib/captp.js:297:29)
      at dispatch (v2/agoric-sdk/packages/captp/lib/captp.js:386:9)
      at Object.onMessage (v2/dapp-loan/_agstate/agoric-servers/dev/vats/captp.js:66:13)
      at /Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:388:23
      at Object.applyMethod (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:353:14)
      at doIt (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:395:67)
    
    Error#6 ERROR_NOTE: Caused by: (Error#7)
    Error#6
      Error#7: Event: 1193.1
         at trackTurns (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/track-turns.js:44:24)
        at handle (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:396:27)
        at Function.applyMethod (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:312:14)
        at Function.applyMethod (/Users/katesills/code/agoric-sdk/packages/tame-metering/src/tame.js:172:20)
        at Proxy.eval (v2/agoric-sdk/packages/eventual-send/src/E.js:37:49)
        at Object.inbound (v2/dapp-loan/_agstate/agoric-servers/dev/vats/vat-http.js:181:61)
        at /Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:388:23
        at Object.applyMethod (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:353:14)
        at doIt (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:395:67)
        at /Users/katesills/code/agoric-sdk/packages/eventual-send/src/track-turns.js:61:22
      
      Error#7 ERROR_NOTE: Caused by: (Error#8)
      Error#7
        Error#8: Event: 1192.1
           at trackTurns (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/track-turns.js:44:24)
          at handle (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:396:27)
          at Function.applyMethod (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:312:14)
          at Function.applyMethod (/Users/katesills/code/agoric-sdk/packages/tame-metering/src/tame.js:172:20)
          at Object.deliver (kernel/packages/SwingSet/src/kernel/liveSlots.js:423:28)
          at eval (kernel/packages/SwingSet/src/kernel/vatManager/deliver.js:50:48)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:93:5)
        
TypeError#5 ERROR_NOTE: Sent as error:captp:http://127.0.0.1#2
SwingSet: v2: Temporary logging of sent error (TypeError#5)

```

and in the deploy script terminal:

```
katesills@Kates-MacBook-Pro dapp-loan % ./test.sh
Open CapTP connection to ws://127.0.0.1:8000/private/captp..........ooooooooooooooooooooooooooooooooooo
agoric: deploy: running /Users/katesills/code/dapp-loan/contract/scripts/setup/startPeriodAsyncIterable.js
start response public facet is working
Open CapTP connection to ws://127.0.0.1:8000/private/captp...o
agoric: deploy: running /Users/katesills/code/dapp-loan/contract/scripts/setup/testPeriodAsyncIterable.js
test response public facet is working
test the periodAsyncIterable with simple observer
periodAsyncIterable Alleged: Presence bundle o-24 <[Object: null prototype] [Alleged: Presence bundle o-24] {}> [Alleged: Presence bundle o-24] {}
after observeIteration
CapTP bundle exception: (TypeError#1)

  TypeError#1: Cannot convert a Symbol value to a string
     at fullRevive (/Users/katesills/code/agoric-sdk/packages/marshal/src/marshal.js:743:34)
    at unserialize (/Users/katesills/code/agoric-sdk/packages/marshal/src/marshal.js:795:19)
    at CTP_RETURN (/Users/katesills/code/agoric-sdk/packages/captp/lib/captp.js:327:16)
    at dispatch (/Users/katesills/code/agoric-sdk/packages/captp/lib/captp.js:386:9)
    at WebSocket.<anonymous> (/Users/katesills/code/agoric-sdk/packages/agoric-cli/lib/deploy.js:109:13)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.EventEmitter.emit (domain.js:485:12)
    at Receiver.receiverOnMessage (/Users/katesills/code/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.EventEmitter.emit (domain.js:485:12)
    at Receiver.dataMessage (/Users/katesills/code/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
    at Receiver.getData (/Users/katesills/code/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
    at Receiver.startLoop (/Users/katesills/code/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
    at Receiver._write (/Users/katesills/code/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:392:12)
    at writeOrBuffer (_stream_writable.js:374:5)
    at Receiver.Writable.write (_stream_writable.js:314:12)
    at Socket.socketOnData (/Users/katesills/code/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:485:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
  
  TypeError#1 ERROR_NOTE: Received as error:captp:http://127.0.0.1#1
TypeError#1 ERROR_NOTE: Rejection from: (Error#2) : 13 . 0
TypeError#1
  Error#2: Event: 12.1
     at trackTurns (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/track-turns.js:44:24)
    at handle (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:396:27)
    at Function.applyMethod (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:312:14)
    at Proxy.<anonymous> (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/E.js:37:49)
    at observeIteration (/Users/katesills/code/agoric-sdk/packages/notifier/src/asyncIterableAdaptor.js:138:60)
    at deployContract (/Users/katesills/code/dapp-loan/contract/scripts/setup/testPeriodAsyncIterable.js:25:3)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async WebSocket.<anonymous> (/Users/katesills/code/agoric-sdk/packages/agoric-cli/lib/deploy.js:228:13)
  
CapTP bundle exception: (TypeError#3)

  TypeError#3: Cannot convert a Symbol value to a string
     at fullRevive (/Users/katesills/code/agoric-sdk/packages/marshal/src/marshal.js:743:34)
    at unserialize (/Users/katesills/code/agoric-sdk/packages/marshal/src/marshal.js:795:19)
    at CTP_RETURN (/Users/katesills/code/agoric-sdk/packages/captp/lib/captp.js:327:16)
    at dispatch (/Users/katesills/code/agoric-sdk/packages/captp/lib/captp.js:386:9)
    at WebSocket.<anonymous> (/Users/katesills/code/agoric-sdk/packages/agoric-cli/lib/deploy.js:109:13)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.EventEmitter.emit (domain.js:485:12)
    at Receiver.receiverOnMessage (/Users/katesills/code/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.EventEmitter.emit (domain.js:485:12)
    at Receiver.dataMessage (/Users/katesills/code/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
    at Receiver.getData (/Users/katesills/code/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
    at Receiver.startLoop (/Users/katesills/code/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
    at Receiver._write (/Users/katesills/code/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:392:12)
    at writeOrBuffer (_stream_writable.js:374:5)
    at Receiver.Writable.write (_stream_writable.js:314:12)
    at Socket.socketOnData (/Users/katesills/code/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:485:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
  
  TypeError#3 ERROR_NOTE: Received as error:captp:http://127.0.0.1#2
TypeError#3 ERROR_NOTE: Rejection from: (Error#4) : 14 . 0
TypeError#3
  Error#4: Event: 12.2
     at trackTurns (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/track-turns.js:44:24)
    at handle (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:396:27)
    at Function.applyMethod (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/index.js:312:14)
    at Proxy.<anonymous> (/Users/katesills/code/agoric-sdk/packages/eventual-send/src/E.js:37:49)
    at recur (/Users/katesills/code/agoric-sdk/packages/notifier/src/asyncIterableAdaptor.js:105:27)
    at /Users/katesills/code/agoric-sdk/packages/notifier/src/asyncIterableAdaptor.js:122:5
    at new Promise (<anonymous>)
    at observeIterator (/Users/katesills/code/agoric-sdk/packages/notifier/src/asyncIterableAdaptor.js:102:10)
    at observeIteration (/Users/katesills/code/agoric-sdk/packages/notifier/src/asyncIterableAdaptor.js:139:10)
    at deployContract (/Users/katesills/code/dapp-loan/contract/scripts/setup/testPeriodAsyncIterable.js:25:3)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async WebSocket.<anonymous> (/Users/katesills/code/agoric-sdk/packages/agoric-cli/lib/deploy.js:228:13)
  
failed (TypeError#3)
```

**To Reproduce**
1. Ensure you are on agoric-sdk `master`
2. In a terminal: `yarn install`
3. `yarn build`
2. In another terminal: Check out the branch `async-iterable-test` on dapp-loan
3. `agoric install`
4. `agoric start --reset -v`
5. In another terminal: `./test.sh`

Files to look at in dapp-loan:
`contract/scripts/setup/startPeriodAsyncIterable.js`
`contract/scripts/setup/periodAsyncIterableContract.js`
`contract/scripts/setup/testPeriodAsyncIterable.js`

**Expected behavior**
I would not expect this usage to throw an error. I would expect it to log the state changes from the `subscription` asyncIterable, even though the asyncIterable is remote. The notifier documentation says:

> The makeNotifierKit() or makeSubscriptionKit() call makes the notifier/updater or 
publication/subscription pair on the producer's site. As a result, both the `iterationObserver` and 
the initial `asyncIterable` are on the producer's site. If Producer Paula sends Consumer Bob 
the `asyncIterable`, Bob receives a possibly remote reference to the asyncIterable. Consumers can 
be remote from the producer of their consumed content.

**Comment by erights** [comment] 2020-12-17 06:58
After #2094 the remaining problem is that SwingSet is still not tolerant of symbols as method names. Following the above reproduction steps now produces a trace that starts with

```
  Error#5: syscall suffered error, shutdown commencing
     at doSyscall (kernel/packages/SwingSet/src/kernel/vatManager/syscall.js:88:13)
    at Object.send (kernel/packages/SwingSet/src/kernel/vatManager/syscall.js:96:24)
    at queueMessage (kernel/packages/SwingSet/src/kernel/liveSlots.js:314:13)
    at Object.applyMethod (kernel/packages/SwingSet/src/kernel/liveSlots.js:80:16)
```

A bit of debugging reveals that this fails when the value of `vatSyscallObject[2]`, the element carrying the method name, is `Symbol.asyncIterator`. This makes sense because we only recently extended marshal.js to send this specific symbol, in order to handle remote async iterables. 

It looks like we use djson.stringify to stringify `vatSyscallObject` objects. But JSON cannot directly serialize symbols. `marshal.js` can of course, but is non-canonical and heavier weight than `djson.stringify`.

The fact that it causes SwingSet to crash is worrisome. Attn @warner @FUDCo

**Comment by warner** [comment] 2020-12-18 17:57
Hrm. The only place we use `djson` is during replay, when we need to compare each new syscall against the transcript. We compare the serialized output of both sides, which of course requires deterministic serialization. But the "vatSyscallObject" comes from *liveslots*, not directly from the vat code, and most of it (the `args=` value) has already been through `marshal()`:

https://github.com/Agoric/agoric-sdk/blob/15022fe7f3fd3d1fc67687f3b010968725c30a7e/packages/SwingSet/src/kernel/vatManager/transcript.js#L48-L58

Ah, ok so while the *arguments* of the syscall have already been marshalled, the method `name` is expected to be a plain string. Within the kernel, we don't inspect the method name very much: the kernel just ferries it to the other vat. But vats will serialize it to record in the transcript, and of course the comms vat needs to encode it into the remote message. Our transcript recording code probably uses plain `JSON.stringify` (on a data structure that includes the crank delivery and every syscall it made), and the playback uses plain `JSON.parse`, and then the code cited above uses `djson` to compare individual syscalls.

In this case, are you invoking a Symbol-named method of the target object?

I'd expect the transcript of the receiving vat to be broken (the inbound delivery would cite a message `name` with whatever `JSON.stringify` did with the Symbol, which probably won't deserialize into the same thing. And I'd expect any attempt to use this over a remote comms connection to fail in the same way (the receiver would get a mangled method name to invoke, and would reject it with something like a TypeError).

To deal with that.. huh. We'd need to extend the notion of "method name" in our kernel+comms message structures to, what, be capdata? Or maybe a degenerate form of capdata, the output of `marshal()` but we insist that the `slots` be empty. That opens up some weirdness.. vats could conceivably "invoke" an arbitrarily-complex "name" on the target object, including Arrays with cycles and who knows what.

But, JS says that property names can be either strings or Symbols, so I guess our messaging layer needs to tolerate anything that JS can emit.

Are there any other possible types for the method name we should be aware of?

**Comment by warner** [comment] 2020-12-18 18:18
Oh, a cleaner approach would be to change our definition of a "message" to include both the method name and the arguments, and marshal them together. I split out the method name from the arguments originally because I thought the kernel should be aware of the name (for debugging, or for unusual cases where the kernel needs to react to a message directly, such as the rejection message it generates when you send to a dead vat, which probably includes the message name). But in practice we almost always leave the name and argument `.body` untouched and unexamined and glued together throughout a delivery's journey through the kernel. We definitely want to keep the target distinct, and we modify the `.slots` at each boundary, and the result promise needs to be visible to the kernel (because the Decider changes at each boundary). But that would be compatible with having vats emit `vatSyscallObjects` as `[targetSlot, serMessage, resultVPID]` instead of `[targetSlot, name, serArgs, resultVPID]`.

But as @FUDCo pointed out, there is a lot of debugging code which knows about this structure and would need to be changed. This task is larger for the second approach (which removes an element from the `vatSyscallObject` structure entirely) than for the first (which merely changes the type and/or interpretation of one element).

**Comment by kriskowal** [comment] 2020-12-18 20:02
It might be possible to avoid the need to transit symbolic method names if we recognize some registered symbol method names as the distinguishing method of some first-class concepts. For example, the marshal layer could recognize all objects implementing `Symbol.asyncIterator` as iterables and specialize the marshaller for that case.

This may also afford an opportunity to specialize the mechanism for transiting async iterables. @erights has some optimizations in mind that would expose the *internals* of the underlying `PromiseQueue<IterationResult<T>>`.

```js
interface EventualIterator<T> = {
  value: Promise<IterationResult<T>>,
  next: EventualIterator<T>
};
```

We could go on to invent a registered `Symbol.eventualIterator` that would provide this mechanism directly, as an optimization in the cases where it’s unnecessary to lift an async iterable.

**Comment by kriskowal** [comment] 2020-12-18 20:06
There are a number of benefits to this optimization on the async iterator protocol, which in turn might need to be opt-in because they pivot from lazy to eager. The promise queue representation transits iterations eagerly instead of lazily, and the sender can more quickly and naturally forget about emitted iteration results. Leaving all mail subscribers’ inboxes instead of publisher’s outboxes is crucial for the performance and scale of pubsub, and increases the liveliness of notifiers.

**Comment by erights** [comment] 2020-12-20 06:41
I am enthused about the possibilities @kriskowal raises at https://github.com/Agoric/agoric-sdk/issues/2092#issuecomment-748294570 and https://github.com/Agoric/agoric-sdk/issues/2092#issuecomment-748292964 . However, I would want to keep SwingSet as ignorant of these as possible. `marshal` does currently recognize only `Symbol.asyncIterator` as a special case. We may add more special cases over time, or we may do something more general like all well-known symbols on the `Symbol` constructor and/or all registered symbols. `marshal` may know about these decisions but SwingSet should not. SwingSet should just pass along symbols, if we decide to do it that way, or some string that encodes the message name, whether string or symbol.

Either of @warner 's solutions at https://github.com/Agoric/agoric-sdk/issues/2092#issuecomment-748232036 and https://github.com/Agoric/agoric-sdk/issues/2092#issuecomment-748241538 would do the encoding. Even the first, using a specialized slotless marshal, produces a different encoding than what we have now for simple string names. Instead of representing the name `foo` as `foo` it would represent it as `"foo"`. If we're going to adopt an incompat encoding anyway, perhaps we should jump to @warner 's second solution. The resulting capData will always like the method name first in a predicable place, so there shouldn't be much stress on the debug tooling which would need to change anyway.

**Comment by erights** [comment] 2021-02-22 08:55
Hi @warner I added you as an additional assignee.

**Comment by erights** [comment] 2021-02-22 08:59
@warner nevermind. I removed you. I was mistaking this for #2481 on this this one is blocked. #2481 is already assigned to you and @FUDCo so all is well.

**Comment by Tartuffo** [comment] 2022-01-20 21:23
Needed for Mainnet 1?

**Comment by erights** [comment] 2022-01-21 07:20
Closed by https://github.com/Agoric/agoric-sdk/issues/2619

**Closed as completed by erights** 2022-01-21 07:20 UTC
Labels: SwingSet
