### ISSUE TITLE
add shutdown() calls to contracts

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#1606] opened 2020-08-24 20:20 UTC
**What is the Problem Being Solved?**

Zoe/Zcf have a method `shutdown()` that exits all the seats and then calls `adminNode.terminate()`. The `terminate()` method used to be a no-op, but now it's wired up. No contracts call it, even though it would make sense for some to.

**Description of the Design**

Add shutdown in atomicSwap and coveredCall, and any other contracts for which it makes sense.

**Security Considerations**

OfferSafety and other guarantees Zoe makes should continue to be enforced.

**Test Plan**

This will allow @FUDCo to validate the functioning of the `terminate()` call.

Either add tests for added functionality, or add issues recording tests to be added.

**Comment by katelynsills** [comment] 2020-08-24 20:25
Is this a dupe of https://github.com/Agoric/agoric-sdk/issues/1433?

**Comment by Chris-Hibbert** [comment] 2020-08-24 21:59
> Is this a dupe of #1433?

Yep.  I closed that one.

**Closed as completed** 2020-08-25 18:25 UTC
Labels: enhancement, Zoe, test
