### ISSUE TITLE
MarkM and the Terrible, Horrible, No Good, Very Bad Logging Report

### ISSUE THREAD

**Issue by dtribble** [Agoric/agoric-sdk#2085] opened 2020-12-14 18:22 UTC

**Comment by katelynsills** [comment] 2020-12-14 19:11
I think this is a duplicate of https://github.com/Agoric/agoric-sdk/issues/2076 which I filed for Mark last week.

**Closed as completed by katelynsills** 2020-12-14 19:11 UTC

**Comment by erights** [comment] 2020-12-14 19:19
Yeah but the issue title is so cool!

**Comment by katelynsills** [comment] 2020-12-14 19:21
> Yeah but the issue title is so cool!

It is much better! 😄
