### ISSUE TITLE
Import Cosmos SDK purses directly from bank to wallet

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#2101] opened 2020-12-17 21:12 UTC
Currently, the faucet that each Agoric client gets access to only provides payments, and the wallet needs to claim them in order to add them to fresh purses.

For virtual purses, like the Cosmos SDK `uagstake` balance, we need to keep the purse intact and use it directly in the new wallet.  This is necessary for it to be linked to the Cosmos SDK balance changes (both increases and decreases).  If the user wants exclusive access to some of the balance, they should create a payment from the virtual purse and claim that payment in a fresh "normal" purse.

The proposed implementation is to have `E(home.bank).getPurseSubscription()` return a `Subscription<{ proposedName: string, purse: Purse, issuer: Issuer }>`.  Then, each wallet can subscribe to get an Iterable of bank's purses.  For the first implementation, the wallet backend will just add those purses without confirmation, but later we should probably have an inbox for inbound bank purses (to allow renaming before import, ignoring the purse, etc).

**Comment by katelynsills** [comment] 2021-02-09 21:42
Is this connected to or a duplicate of #2103?

**Comment by michaelfig** [comment] 2021-02-09 21:57
> Is this connected to or a duplicate of #2103?

Somewhat connected.  "Transfer accounts" are a generalised idea that applies to plugins and dapps.  This "import purses from faucet" will just be for purses that are gifted to the client upon provisioning, not ones from plugins nor dapps.

**Comment by rowgraus** [comment] 2021-03-23 20:49
I'm tagging this ticket with the Beta Treasury Launch milestone unless you think we don't need it @michaelfig.

**Comment by michaelfig** [comment] 2021-03-24 01:32
> I'm tagging this ticket with the Beta Treasury Launch milestone unless you think we don't need it @michaelfig.

MOE and staking tokens are in different worlds and don't yet need to meet.  They will when we accept staking tokens as collateral (or otherwise trade them in the JS economy), or implement Cosmos-level metering in MOE, or implement staking rewards in JS.

It's not that we don't need it.  It's just such an amount of work that I think we can't have it at first.

**Comment by dckc** [comment] 2021-04-20 22:19
@michaelfig I just heard you say we should have uRUN and uBLD at the cosmos level and that we have an issue for it; is there a better issue than this one?

**Comment by michaelfig** [comment] 2021-04-20 22:25
> @michaelfig I just heard you say we should have uRUN and uBLD at the cosmos level and that we have an issue for it; is there a better issue than this one?

This is the right issue for now.

**Comment by michaelfig** [comment] 2021-04-25 21:21
@katelynsills, I'd like to bring your attention to my implementation proposal:

> The proposed implementation is to have E(home.faucet).getPurseSubscription() return a Subscription<[proposedName, Purse]>. Then, each wallet can subscribe to get an Iterable of faucet's purses. For the first implementation, the wallet backend will just add those purses without confirmation, but later we should probably have an inbox for inbound faucet purses (to allow renaming before import, ignoring the purse, etc).

**Comment by michaelfig** [comment] 2021-04-26 18:44
> Can you walk me through a few more details? For instance, I would expect the Cosmos virtual purse to come from something like `home.cosmos`.

That's a reasonable idea, but I'd like to make the source abstract enough not to only be useful for our chain implementation.  There's currently nothing in the vats that understands the chain is a cosmos-based chain specifically.

> `Faucet` sounds like a gift of free money to me, but this is giving the user their own money, just from an underlying source.

Then we should rename `home.faucet`, since it is really the system's way of getting trusted assets into a wallet.  Do you have any suggestions?

> Can you walk me through why we use a subscription? Do we expect this purse to change? Is it building out for the future, or do we expect multiple purses for the same user currently?

We expect multiple purses for the same user.  Currently, one for BLD-ubld and another for RUN-urun.  The subscription is not publishing all the virtual purses for every update, it is only publishing a single (different) virtual purse for each update.

> Also, what does the wallet method look like that consumes the result?

(Answering this question caused the subscription design to change, as we may also need the issuer for a given purse.)

The `faucet/whatever` would be supplied as an argument to the wallet backend's instantiation.  Then the backend would set up a subscriber for `E(faucet/whatever).getPurseSubscription()` and add the inbound `issuer` and `purse` under the `proposedName` without confirmation, as they arrive.  This is all that's necessary for MVP.

> Would a user be able to find the method and use it wrongly to add a purse from another user?

Glad you asked that... it was the main constraint on the design to preserve the security properties you were concerned about  The answer is: no.  That method is only an internal function as part of the wallet backend setup, not exported to anything else (not even the user).

**Comment by dckc** [comment] 2021-04-26 19:02
> > `Faucet` sounds like a gift of free money to me, but this is giving the user their own money, just from an underlying source.
> 
> Then we should rename `home.faucet`, since it is really the system's way of getting trusted assets into a wallet. Do you have any suggestions?

It seems like `home.faucet` won't / shouldn't be available at mainnet at all. Will the RUN and BLD issuers be in `home.agoricNames`?
https://github.com/Agoric/agoric-sdk/blob/e0f0633a80ed96995c99a5ae092974fca84e6f3d/packages/vats/src/bootstrap.js#L469

perhaps that's beside the point...

how about `home.account`?

p.s. I see `test.serial('home.wallet - central issuer setup', ...)` in https://github.com/Agoric/agoric-sdk/blob/master/packages/solo/test/test-home.js but I guess that's on the solo side and your question is about home on the chain side.

**Comment by katelynsills** [comment] 2021-04-26 21:15
>

**Comment by katelynsills** [comment] 2021-04-26 21:22
> Then we should rename home.faucet, since it is really the system's way of getting trusted assets into a wallet. Do you have any suggestions?

Sure, here's a few more options: `home.chain`, `home.basement`, `home.underlyingChain`, `home.baseAccounts`. 

> The subscription is not publishing all the virtual purses for every update, it is only publishing a single (different) virtual purse for each update.

I'm not sure I understood this. What would constitute an update? A new `bank` account? Certainly not just a balance change on the cosmos-level, right? Because that would still be represented by the same virtual purse, and no need to get a new one? I think there's something I'm still missing here.

> The faucet/whatever would be supplied as an argument to the wallet backend's instantiation. Then the backend would set up a subscriber for E(faucet/whatever).getPurseSubscription() and add the inbound issuer and purse under the proposedName without confirmation, as they arrive. This is all that's necessary for MVP.

Sounds good to me!

> Glad you asked that... it was the main constraint on the design to preserve the security properties you were concerned about The answer is: no. That method is only an internal function as part of the wallet backend setup, not exported to anything else (not even the user).

Yay, I'm so glad! Thanks so much! 👍

**Comment by michaelfig** [comment] 2021-04-26 22:21
> I'm not sure I understood this. What would constitute an update?

A new virtual purse, for a specific account+denomination combination.

> Certainly not just a balance change on the cosmos-level, right?

Yes, you're right.

**Comment by michaelfig** [comment] 2021-04-28 18:59
How about `home.bank`, since we're specifically bridging to Cosmos banking?

**Comment by katelynsills** [comment] 2021-04-28 19:14
> How about `home.bank`, since we're specifically bridging to Cosmos banking?

Sounds great to me!

**Closed as completed** 2021-05-06 01:05 UTC
Labels: wallet
