### ISSUE TITLE
XS reports TypeError differently than Node?

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1780] opened 2020-09-16 01:57 UTC
While reviewing code which did something like:

```js
function buildRootObject(vatPowers) {
  const log = vatPowers.testLog;
  return harden({
    bootstrap() {
      log(stuff);
    }
  });
}
```

we saw XS emit a `TypeError("?.bootstrap: no function")`. We know that `vatPowers` was an object, but it lacked a `testLog` property.

I *think* this meant:

* there was an object (which we know of as the root object)
* XS did not have a good name for that object (perhaps sometimes it does), so it describes it as `?`
* a method (`bootstrap`) was being invoked on that object
* while that method was being invoked, someone tried to invoke a non-function (i.e. `vatPowers.testLog`, aka `log`, which was `undefined`

I'm thinking that the `?.bootstrap` is sort of a stripped down stack trace.

Anyways, I figured I should record what we saw so we can think about what we want the observable Error behavior to be, and as a guide to debugging errors during XS. I'm guessing @erights 's new `assert` library will overlap with this (if the `TypeError` doesn't have a locally-visible `.message` property then we'll have an easier time making it deterministic), but I'm not sure if that `TypeError` was created in a way that his library will be able to control.

**Comment by erights** [comment] 2020-09-16 02:07
I don't expect my `assert` library to make any difference here.

What is the XS situation re stack traces?

**Comment by dckc** [comment] 2020-10-14 19:50
stack traces... I'm not aware of any, other than in the debugger.

Is there some way I could test?

**Comment by dckc** [comment] 2021-03-04 00:46
I just ran into another while working on zoe tests on XS (#370):

```
{"actual":"(host): cannot coerce undefined to object",
 "expected":"undefined is not iterable (cannot read property Symbol(Symbol.iterator))"}

{
  status: 'not ok',
  id: 29,
  message: 'no expected keywordRecord gets an error',
  filename: 'test/unitTests/zcf/test-zoeHelpersWZcf.js',
  label: 'zoeHelper with zcf - assertIssuerKeywords'
}
```
https://github.com/Agoric/agoric-sdk/blob/master/packages/zoe/test/unitTests/zcf/test-zoeHelpersWZcf.js#L260

**Comment by erights** [comment] 2021-03-04 02:23
Yeah, that test case with that string appearing literally is now revealed to be a buggy test. It is buggy because it is testing for the contents of an error message string generated not by our code but by the JavaScript engine. Engines differ all over the place on the contents of these strings, as the spec allows them to.

We should fix all of these not to check the error message. However, that will be a long battle because there's no way to automatically distinguish them. I suggest that ava-xs have a mode switch for ignoring the only contents of these error strings. On this pass we should set it to ignore mode. Once things are otherwise working, a separate lower priority task would be to set the flag the other way, in order to flush out such bad comparisons from our code.

Sorry. We should have seen this coming.

**Comment by erights** [comment] 2021-03-04 02:29
See https://github.com/Agoric/agoric-sdk/issues/2574

**Comment by dckc** [comment] 2021-03-04 02:41
ok... then it seems that different messages from different hosts is not a bug. I'll close this one.

**Closed as completed by dckc** 2021-03-04 02:41 UTC
Labels: invalid, SwingSet
