### ISSUE TITLE
inviteHandle and offerHandle currently refer to the same object

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#805] opened 2020-03-29 18:52 UTC
In this line, `(buyI)nviteHandles` is used 

https://github.com/Agoric/agoric-sdk/blob/5505d6c639e6135db7f4e700bd0fd1fc392858be/packages/zoe/src/contracts/simpleExchange.js#L106

Meanwhile, the doc talks about `offerHandles` like in https://agoric.com/documentation/zoe/api/zoe.html#zoe-getoffers-offerhandles

and the [makeInvite doc](https://agoric.com/documentation/zoe/api/zoe-contract-facet.html#zcf-makeinvite-seat-customproperties) suggests that an `inviteHandle` is returned alongside the `invite`

My understanding is that the inviteHandle and offerHandle are the same thing
This confused me for some time while working on the opera ticket contract

I think it'd be best to only use one name consistently

I would argue in favor of `offerHandle`. One benefit i see is that `makeInvite` would return `{ invite, offerHandle }` which i find less confusing than { invite, inviteHandle }`

I wonder whether `zoeHandle` could be a viable candidate

**Comment by DavidBruant** [comment] 2020-03-29 18:53
I'm taking the initiative to mark this issue as `hackathon-release` since i believe it is a small amount of work and help remove a major confusion i had about Zoe

**Comment by katelynsills** [comment] 2020-03-30 20:39
Yup, `offerHandle` is the same thing as `inviteHandle`. I would support using the term `offerHandle`. One wrinkle is that the `handle` in the extent of the invite is the `offerHandle`/`inviteHandle` and that is a bit awkward to call an `offerHandle`. But, I agree with you that it's better to consistently use the same name in all forms.

**Comment by DavidBruant** [comment] 2020-04-01 14:03
> One wrinkle is that the handle in the extent of the invite

I'm starting to think that given there are several handle types, maybe `handle` alone should never be used in Zoe/ERTP in order to reduce confusion

**Comment by katelynsills** [comment] 2020-04-01 18:01
Next step: look at what functions use the inviteHandle/offerHandle and analyze

**Comment by DavidBruant** [comment] 2020-04-03 14:47
Ok, I think my current thinking is that they refer to the same thing... but shouldn't

I spent some time in the code and i think the crime happens here:

https://github.com/Agoric/agoric-sdk/blob/cf9346dde2a3fcea435af5149cb958aad5a8016d/packages/zoe/src/zoe.js#L107-L117

Here `handle` means `inviteHandle`

https://github.com/Agoric/agoric-sdk/blob/cf9346dde2a3fcea435af5149cb958aad5a8016d/packages/zoe/src/zoe.js#L377-L385

and here, the destructuing of the same object leads to the same `handle` being an `offerHandle`

As [i suggest in another issue](https://github.com/Agoric/agoric-sdk/issues/810#issuecomment-608469029), i think both need to exist separatly:
- The inviteHandle is useful because invites are payments and they are the unique/stable part of the payment that zoe can refer to to get back the contract instance/seat
- The offerHandle is useful for the asset allocation


> I'm starting to think that given there are several handle types, maybe `handle` alone should never be used in Zoe/ERTP in order to reduce confusion

+2

**Comment by DavidBruant** [comment] 2020-04-04 20:02
I think i've found a security concern with having the offerHandle available as part of the invite extent

The invite is an ERTP payment. I imagine this is for the purpose of being able to consider the invite an asset that can be traded in contracts, traded between people, etc. So, some Zoe invites will probably be passed around between many parties before being used\
If the offerHandle is available as part of the invite, then everyone who kept a reference to the offerHandle (and that's possible to do even after the invite itself has been `claim`ed by someone else) can call `zoe.getOffer(offerHandle)` even if they are not the person who redeemed the invite

As a consequence, all the parties who had the invite payment at some point but didn't redeem it still [have access to](https://github.com/Agoric/agoric-sdk/blob/e2c311b4d536f18d6966b0fc10721b581fd1368a/packages/zoe/src/zoe.js#L448-L456) the `proposal` and `currentAllocations` of related to the offer associated with who did redeem the invite (they can also poll currentAllocations to see when/how things change in the contract too)

That's potentially a lot of people who have access to informations about the redeemer they probably shouldn't have access to\
The redeemer cannot prevent being listened, cannot know who is listening and cannot stop being listened (until offer completion)

I think that this is sufficient reason to not put the `offerHandle` in the invite extent

I think this add weight to [the idea of having separate `inviteHandle` and `offerHandle`](https://github.com/Agoric/agoric-sdk/issues/810#issuecomment-608469029)

**Comment by erights** [comment] 2020-04-04 21:42
Hi @DavidBruant this is a good point. I agree that this level of access is implied, and that it is inappropriate. I don't yet have an opinion about the proposed alternative but certainly agree that this observation adds weight to that idea.

**Comment by katelynsills** [comment] 2020-04-06 02:06
I think the security concern is filed here: https://github.com/Agoric/agoric-sdk/issues/773

The current allocations and proposal are not intended to be private, since the use is on a public blockchain.

**Comment by DavidBruant** [comment] 2020-04-06 07:22
> The current allocations and proposal are not intended to be private, since the use is on a public blockchain.

oh... i had forgotten about this part

The implictations of this throw me into a spiral of questions. For another time/issue probably

**Comment by erights** [comment] 2020-04-08 00:39
> The current allocations and proposal are not intended to be private, since the use is on a public blockchain.

I think that's a fine rationale for postponing this but leaving it open. Even on a public chain, we wish the useful transparency to be reified as object protocol (as it is here) and the transparency reified as object protocol to be sensible even when the computation is not otherwise transparent. @DavidBruant 's point shows that the current API fails at the second.

This is all in addition to #773 which is rather different.

**Comment by katelynsills** [comment] 2020-04-15 18:14
Dupe of #889

**Closed as completed by katelynsills** 2020-04-15 18:14 UTC
Labels: documentation, Zoe
