### ISSUE TITLE
In error messages, displaying payments as `{ getAllegedBrand: [Function: getAllegedBrand] }` is not very helpful

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#989] opened 2020-04-23 10:51 UTC
Derived from a comment in support chat
But also based on my experience

The message that the person received was: 

> extent has duplicates: { getAllegedBrand: [Function: getAllegedBrand] } and { getAllegedBrand: [Function: getAllegedBrand] }

but as is, the message is unhelpful because it does not contain a description of the extent or the issuer.

I think that having more context in the error message would help making the error more helpful

**Comment by katelynsills** [comment] 2020-04-23 23:31
I think we can close this, because it is actually printing the extent. The problem is that in this case, the extent is a payment, so there is no information printed besides the `getAllegedBrand` method. We wouldn't be able to improve the display-ability of payments in this scenario because we don't want them to be there in the first place.

**Closed as completed** 2020-04-24 21:14 UTC
Labels: ERTP

**Comment by erights** [comment] 2020-04-25 05:13
See #804 for our plan that enables presences to carry descriptions
